package:
  name: m2-libgdbm
  version: 1.23.1
source:
  - url: {{ msys2_pkg_url }}/libgdbm-1.23-1-x86_64.pkg.tar.zst
    sha256: 282cb95bc1ffb51b46179dbe502820c64fcd86c79cffb81aa241b3c6e008c3bf
    folder: binary

build:
  number: 0
  noarch: generic

requirements:
  host:
    - m2-conda-epoch
  run:
    - m2-gcc-libs
    - m2-libreadline
    - m2-libiconv
    - m2-libintl
    - m2-ncurses

about:
  home: https://www.gnu.org/software/gdbm/gdbm.html
  license: GPL3
  summary: GNU database library

extra:
  recipe-maintainers:
    - isuruf
