package:
  name: mingw-w64-ucrt-x86_64-zlib
  version: 1.3.1
source:
  - url: {{ m2w64_ucrt64_pkg_url }}/mingw-w64-ucrt-x86_64-zlib-1.3-1-any.pkg.tar.zst
    sha256: 89719f7c4e40a8276bb921384caed69eb2626e666aeaf43a7d9f65f33f5a09c0
    folder: binary

build:
  number: 0

requirements:
  run:

  run_constrained:
    - msys2-conda-epoch <0.0a0

about:
  home: https://www.zlib.net/
  license: Zlib
  summary: |
    Compression library implementing the deflate compression method found in gzip and PKZIP (mingw-w64)

extra:
  recipe-maintainers:
    - isuruf
