package:
  name: m2-perl-http-message
  version: 6.44.1
source:
  - url: {{ msys2_pkg_url }}/perl-HTTP-Message-6.44-1-any.pkg.tar.zst
    sha256: a1b9529f798daf3edc4cd3f3b262aee170515cbe635a27fad0512aa67f87d70d
    folder: binary

build:
  number: 0
  noarch: generic

requirements:
  host:
    - m2-conda-epoch
  run:
    - m2-perl >=5.8.8
    - m2-perl-clone
    - m2-perl-encode-locale >=1
    - m2-perl-io-html
    - m2-perl-http-date >=6
    - m2-perl-lwp-mediatypes >=6
    - m2-perl-uri >=1.10

about:
  home: https://metacpan.org/release/HTTP-Message
  license: PerlArtistic
  summary: |
    HTTP style messages

extra:
  recipe-maintainers:
    - isuruf
