package:
  name: m2-perl-HTTP-Cookies
  version: 6.10.2
source:
  - url: {{ msys2_pkg_url }}/perl-HTTP-Cookies-6.10-2-any.pkg.tar.zst
    sha256: b6da8b56fcb4134c78cdedd87bbd8aa749a6aec07dcee7fb9432a20fdf1bcf29
    folder: binary

build:
  number: 0
  noarch: generic

requirements:
  host:
    - m2-conda-epoch
  run:
    - m2-perl>=5.8.8
    - m2-perl-HTTP-Date>=6
    - m2-perl-HTTP-Message

about:
  home: https://metacpan.org/release/HTTP-Cookies
  license: PerlArtistic
  summary: HTTP cookie jars
