package:
  name: mingw-w64-ucrt-x86_64-tools-git
  version: 9.0.0.6454.b4445ee52.1
source:
  - url: {{ m2w64_ucrt64_pkg_url }}/mingw-w64-ucrt-x86_64-tools-git-9.0.0.6454.b4445ee52-1-any.pkg.tar.zst
    sha256: e68a2c1a2e4ad534b7274420a1f6283f8d00e6d0c9a68000b9cd52513427f121
    folder: binary

build:
  number: 0

requirements:
  run:
    - mingw-w64-ucrt-x86_64-gcc-libs
  run_constrained:
    - msys2-conda-epoch <0.0a0

about:
  home: https://mingw-w64.sourceforge.io/
  license: custom
  summary: |
    MinGW-w64 tools

extra:
  recipe-maintainers:
    - isuruf
