package:
  name: m2-perl-http-daemon
  version: 6.16.1
source:
  - url: {{ msys2_pkg_url }}/perl-HTTP-Daemon-6.16-1-any.pkg.tar.zst
    sha256: 493f314ee2573916ca88d7615c00311d9ee5c901df96b356a0d319bc19f751d0
    folder: binary

build:
  number: 0
  noarch: generic

requirements:
  host:
    - m2-conda-epoch
  run:
    - m2-perl
    - m2-perl-http-date
    - m2-perl-http-message
    - m2-perl-io-socket-ip
    - m2-perl-lwp-mediatypes

about:
  home: https://metacpan.org/dist/HTTP-Daemon
  license: Artistic-1.0-Perl
  summary: |
    A simple http server class

extra:
  recipe-maintainers:
    - isuruf
