package:
  name: m2-libpcre2_16
  version: 10.42.1
source:
  - url: {{ msys2_pkg_url }}/libpcre2_16-10.42-1-x86_64.pkg.tar.zst
    sha256: 9660790660bfc6b17fb0ba2ddec37f339f4418a0228fc528dc28a4210142eeb7
    folder: binary

build:
  number: 0
  noarch: generic

requirements:
  host:
    - m2-conda-epoch
  run:
    - m2-gcc-libs

about:
  home: https://www.pcre.org/
  license: BSD
  summary: A library that implements Perl 5-style regular expressions
