package:
  name: m2-perl-Try-Tiny
  version: 0.31.1
source:
  - url: {{ msys2_pkg_url }}/perl-Try-Tiny-0.31-1-any.pkg.tar.zst
    sha256: 3e1f108c8290235e74c0975382edfbb3b8ce805cfa192b6cce982930cb503630
    folder: binary

build:
  number: 0
  noarch: generic

requirements:
  host:
    - m2-conda-epoch
  run:
    - m2-perl

about:
  home: https://metacpan.org/release/Try-Tiny
  license: MIT
  summary: Minimal try/catch with proper localization of $@
