package:
  name: m2-nano
  version: 7.2.1
source:
  - url: {{ msys2_pkg_url }}/nano-7.2-1-x86_64.pkg.tar.zst
    sha256: 43b4fb8d23c2a5ea3dcdce2c0da61694979a9f9ba21acc4511ae11241617996b
    folder: binary

build:
  number: 0
  noarch: generic

requirements:
  host:
    - m2-conda-epoch
  run:
    - m2-file
    - m2-libintl
    - m2-ncurses
    - m2-bash

about:
  home: https://www.nano-editor.org
  license: GPL-3.0-or-later
  summary: |
    Pico editor clone with enhancements

extra:
  recipe-maintainers:
    - isuruf
