package:
  name: versioneer
  version: "0.15"

source:
  fn: versioneer-0.15.tar.gz
  url: https://pypi.python.org/packages/source/v/versioneer/versioneer-0.15.tar.gz
  md5: 38c8810defbc26721b7e4a419c040892
#  patches:
   # List any patch files here
   # - fix.patch

# build:
  # noarch_python: True
  # preserve_egg_dir: True
  # entry_points:
    # Put any entry points (scripts to be generated automatically) here. The
    # syntax is module:function.  For example
    #
    # - versioneer = versioneer:main
    #
    # Would create an entry point called versioneer that calls versioneer.main()


  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  # number: 1

requirements:
  build:
    - python
    - setuptools

  run:
    - python

# test:
  # Python imports
  # imports:

  # commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.


  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  # requires:
    # Put any additional test requirements here.  For example
    # - nose

about:
  home: https://github.com/warner/python-versioneer
  license: public domain
  summary: 'Easy VCS-based management of project version strings'

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
