package:
  name: m2-openssh
  version: 9.4p1.1
source:
  - url: {{ msys2_pkg_url }}/openssh-9.4p1-1-x86_64.pkg.tar.zst
    sha256: c719753161881a616ca38bac39e6ddb0b6f251fd07f1d4de88dc8908e1bcd7bf
    folder: binary

build:
  number: 0
  noarch: generic

requirements:
  host:
    - m2-conda-epoch
  run:
    - m2-heimdal
    - m2-libedit
    - m2-libxcrypt
    - m2-libfido2
    - m2-openssl

about:
  home: https://www.openssh.com/portable.html
  license: custom:BSD
  summary: Free version of the SSH connectivity tools
