package:
  name: mingw-w64-ucrt-x86_64-gcc-libgfortran
  version: 13.2.0.2
source:
  - url: {{ m2w64_ucrt64_pkg_url }}/mingw-w64-ucrt-x86_64-gcc-libgfortran-13.2.0-2-any.pkg.tar.zst
    sha256: 8a19a81300229ed7e53fea7b9dcc3dc998e9f8f615482c712993bdb4f7e579da
    folder: binary

build:
  number: 0

requirements:
  run:
    - mingw-w64-ucrt-x86_64-gcc-libs =13.2.0-2
  run_constrained:
    - msys2-conda-epoch <0.0a0

about:
  home: https://gcc.gnu.org
  license: GPL
  summary: |
    GNU Compiler Collection (libgfortran) for MinGW-w64

extra:
  recipe-maintainers:
    - isuruf
