package:
  name: m2-time
  version: 1.9.3
source:
  - url: {{ msys2_pkg_url }}/time-1.9-3-x86_64.pkg.tar.zst
    sha256: 149a03422d0680e3a66c704de3a472ef628ed354149deca46bbfea69ba9d2d79
    folder: binary

build:
  number: 0
  noarch: generic

requirements:
  host:
    - m2-conda-epoch
  run:


about:
  home: https://www.gnu.org/directory/time.html
  license: GPL
  summary: Utility for monitoring a program's use of system resources
