package:
  name: m2-dash
  version: 0.5.12.1
source:
  - url: {{ msys2_pkg_url }}/dash-0.5.12-1-x86_64.pkg.tar.zst
    sha256: 6499dcccdb7e3a58e473c695bf7de27cbb3579759e3f6312b002815fafae1147
    folder: binary

build:
  number: 0
  noarch: generic

requirements:
  host:
    - m2-conda-epoch
  run:
    - m2-grep
    - m2-sed
    - m2-filesystem

about:
  home: http://gondor.apana.org.au/~herbert/dash/
  license: BSD
  summary: |
    A POSIX compliant shell that aims to be as small as possible

extra:
  recipe-maintainers:
    - isuruf
