package:
  name: m2-libgcrypt
  version: 1.9.4.1
source:
  - url: {{ msys2_pkg_url }}/libgcrypt-1.9.4-1-x86_64.pkg.tar.zst
    sha256: 5677ac935741ca90dfed41f582508ca6cdd130f4c518760a9aabd25bf3dddb85
    folder: binary

build:
  number: 0
  noarch: generic

requirements:
  host:
    - m2-conda-epoch
  run:
    - m2-libgpg-error

about:
  home: https://gnupg.org
  license: LGPL
  summary: General purpose cryptographic library based on the code from GnuPG

extra:
  recipe-maintainers:
    - isuruf
