package:
  name: m2-bash
  version: 5.2.015.1
source:
  - url: {{ msys2_pkg_url }}/bash-5.2.015-1-x86_64.pkg.tar.zst
    sha256: 0b2faed7a6894e71c3f7c1fc90b8e82c07581a452b4bf53121bfb8498244f5a7
    folder: binary

build:
  number: 0
  noarch: generic

requirements:
  host:
    - m2-conda-epoch
  run:
    - m2-filesystem

about:
  home: https://www.gnu.org/software/bash/bash.html
  license: GPL
  summary: |
    The GNU Bourne Again shell

extra:
  recipe-maintainers:
    - isuruf
