package:
  name: posix
  version: 2.0.0
build:
  number: 0
  noarch: generic
requirements:
  host:
  - m2-conda-epoch
  run:
  - m2-base
  - m2-make
  - m2-tar
  - m2-zip
  - m2-unzip
  - m2-diffutils
