package:
  name: m2-libzstd
  version: 1.5.5.1
source:
  - url: {{ msys2_pkg_url }}/libzstd-1.5.5-1-x86_64.pkg.tar.zst
    sha256: 6dd1feaefc0c0b07a2e2c81efe7616a7a6d3b0d08536c21b84a3476c44cfbc46
    folder: binary

build:
  number: 0
  noarch: generic

requirements:
  host:
    - m2-conda-epoch
  run:
    - m2-gcc-libs

about:
  home: https://facebook.github.io/zstd/
  license: BSD
  summary: Zstandard - Fast real-time compression algorithm

extra:
  recipe-maintainers:
    - isuruf
