package:
  name: r-doparallel
  # Note that conda versions cannot contain -, so any -'s in the version have
  # been replaced with _'s.
  version: "1.0.8"

source:
  fn: doParallel_1.0.8.tar.gz
  url:
    - http://cran.r-project.org/src/contrib/doParallel_1.0.8.tar.gz
    - http://cran.r-project.org/src/contrib/Archive/doParallel/doParallel_1.0.8.tar.gz


  # You can add a hash for the file here, like md5 or sha1
  # md5: 49448ba4863157652311cc5ea4fea3ea
  # sha1: 3bcfbee008276084cbb37a2b453963c61176a322
  # patches:
   # List any patch files here
   # - fix.patch

build:
  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  # number: 1

  # This is required to make R link correctly on Linux.
  rpaths:
    - lib/R/lib/
    - lib/

# Suggests: caret, mlbench, rpart
requirements:
  build:
    - r
    - r-foreach >=1.2.0
    - r-iterators >=1.0.0

  run:
    - r
    - r-foreach >=1.2.0
    - r-iterators >=1.0.0

test:
  commands:
    # You can put additional test commands to be run here.
    - $R -e "library('doParallel')" # [not win]
    - "\"%R%\" -e \"library('doParallel')\"" # [win]

  # You can also put a file called run_test.py, run_test.sh, or run_test.bat
  # in the recipe that will be run at test time.

  # requires:
    # Put any additional test requirements here.

about:
  #home:
  license: GPL-2
  summary: Provides a parallel backend for the %dopar% function using the parallel package.

# The original CRAN metadata for this package was:

# Package: doParallel
# Type: Package
# Title: Foreach parallel adaptor for the parallel package
# Version: 1.0.8
# Author: Revolution Analytics, Steve Weston
# Maintainer: Revolution Analytics <packages@revolutionanalytics.com>
# Description: Provides a parallel backend for the %dopar% function using the parallel package.
# Depends: R (>= 2.14.0), foreach(>= 1.2.0), iterators(>= 1.0.0), parallel, utils
# Suggests: caret, mlbench, rpart
# Enhances: compiler, RUnit
# License: GPL-2
# Repository: CRAN
# Repository/R-Forge/Project: doparallel
# Repository/R-Forge/Revision: 13
# Repository/R-Forge/DateTimeStamp: 2014-02-25 19:30:09
# Date/Publication: 2014-02-28 20:42:20
# Packaged: 2014-02-25 23:42:05 UTC; rforge
# NeedsCompilation: no

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
