package:
  name: m2-make
  version: 4.4.1.1
source:
  - url: {{ msys2_pkg_url }}/make-4.4.1-1-x86_64.pkg.tar.zst
    sha256: d36d2f8e976fd43cb6868d79745937a7391937f70b469544b3d16cd9708765df
    folder: binary

build:
  number: 0
  noarch: generic

requirements:
  host:
    - m2-conda-epoch
  run:
    - m2-libintl
    - m2-bash

about:
  home: https://www.gnu.org/software/make
  license: GPL3
  summary: |
    GNU make utility to maintain groups of programs

extra:
  recipe-maintainers:
    - isuruf
