package:
  name: m2-perl-io-stringy
  version: 2.113.1
source:
  - url: {{ msys2_pkg_url }}/perl-IO-Stringy-2.113-1-any.pkg.tar.zst
    sha256: 786ec871dfd889ddd3411fafade368d26a1902c1bc51c3a5fe0ea9f36853b449
    folder: binary

build:
  number: 0
  noarch: generic

requirements:
  host:
    - m2-conda-epoch
  run:
    - m2-perl

about:
  home: https://metacpan.org/release/IO-stringy
  license: GPL
  summary: I/O on in-core objects like strings/arrays

extra:
  recipe-maintainers:
    - isuruf
