package:
  name: r-diagrammer
  # Note that conda versions cannot contain -, so any -'s in the version have
  # been replaced with _'s.
  version: "0.7"

source:
  fn: DiagrammeR_0.7.tar.gz
  url:
    - http://cran.r-project.org/src/contrib/DiagrammeR_0.7.tar.gz
    - http://cran.r-project.org/src/contrib/Archive/DiagrammeR/DiagrammeR_0.7.tar.gz


  # You can add a hash for the file here, like md5 or sha1
  # md5: 49448ba4863157652311cc5ea4fea3ea
  # sha1: 3bcfbee008276084cbb37a2b453963c61176a322
  # patches:
   # List any patch files here
   # - fix.patch

build:
  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  # number: 1

  # This is required to make R link correctly on Linux.
  rpaths:
    - lib/R/lib/
    - lib/

# Suggests: knitr, V8 (>= 0.5)
requirements:
  build:
    - r
    - r-htmlwidgets >=0.3.2
    - r-rstudioapi >=0.2
    - r-stringr >=1.0.0

  run:
    - r
    - r-htmlwidgets >=0.3.2
    - r-rstudioapi >=0.2
    - r-stringr >=1.0.0

test:
  commands:
    # You can put additional test commands to be run here.
    - $R -e "library('DiagrammeR')" # [not win]
    - "\"%R%\" -e \"library('DiagrammeR')\"" # [win]

  # You can also put a file called run_test.py, run_test.sh, or run_test.bat
  # in the recipe that will be run at test time.

  # requires:
    # Put any additional test requirements here.

about:
  #home:
  license: MIT + file LICENSE
  summary: Create graph diagrams and flowcharts using R.

# The original CRAN metadata for this package was:

# Package: DiagrammeR
# Type: Package
# Title: Create Diagrams and Flowcharts Using R
# Version: 0.7
# Date: 2015-06-11
# Authors@R: c( person("Knut", "Sveidqvist", role = c("aut", "cph"), comment = "mermaid.js library in htmlwidgets/lib, http://github.com/knsv/mermaid/"), person("Mike", "Bostock", role = c("aut", "cph"), comment = "d3.js library in htmlwidgets/lib, http://d3js.org"), person("Chris", "Pettitt", role = c("aut", "cph"), comment = "dagre-d3.js library in htmlwidgets/lib, http://github.com/cpettitt/dagre-d3"), person("Mike", "Daines", role = c("aut", "cph"), comment = "viz.js library in htmlwidgets/lib, http://github.com/mdaines/viz.js/"), person("Richard", "Iannone", role = c("aut", "cre"), comment = "R interface", email = "riannone@me.com") )
# Maintainer: Richard Iannone <riannone@me.com>
# Description: Create graph diagrams and flowcharts using R.
# License: MIT + file LICENSE
# Imports: htmlwidgets (>= 0.3.2), rstudioapi (>= 0.2), stringr (>= 1.0.0)
# Suggests: knitr, V8 (>= 0.5)
# VignetteBuilder: knitr
# NeedsCompilation: no
# Packaged: 2015-06-11 16:50:44 UTC; riannone
# Author: Knut Sveidqvist [aut, cph] (mermaid.js library in htmlwidgets/lib, http://github.com/knsv/mermaid/), Mike Bostock [aut, cph] (d3.js library in htmlwidgets/lib, http://d3js.org), Chris Pettitt [aut, cph] (dagre-d3.js library in htmlwidgets/lib, http://github.com/cpettitt/dagre-d3), Mike Daines [aut, cph] (viz.js library in htmlwidgets/lib, http://github.com/mdaines/viz.js/), Richard Iannone [aut, cre] (R interface)
# Repository: CRAN
# Date/Publication: 2015-06-11 21:46:52

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
