package:
  name: r-irlba
  # Note that conda versions cannot contain -, so any -'s in the version have
  # been replaced with _'s.
  version: "1.0.3"

source:
  fn: irlba_1.0.3.tar.gz
  url:
    - http://cran.r-project.org/src/contrib/irlba_1.0.3.tar.gz
    - http://cran.r-project.org/src/contrib/Archive/irlba/irlba_1.0.3.tar.gz


  # You can add a hash for the file here, like md5 or sha1
  # md5: 49448ba4863157652311cc5ea4fea3ea
  # sha1: 3bcfbee008276084cbb37a2b453963c61176a322
  # patches:
   # List any patch files here
   # - fix.patch

build:
  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  # number: 1

  # This is required to make R link correctly on Linux.
  rpaths:
    - lib/R/lib/
    - lib/


requirements:
  build:
    - r
    - r-matrix # [not win]

  run:
    - r
    - r-matrix # [not win]

test:
  commands:
    # You can put additional test commands to be run here.
    - $R -e "library('irlba')" # [not win]
    - "\"%R%\" -e \"library('irlba')\"" # [win]

  # You can also put a file called run_test.py, run_test.sh, or run_test.bat
  # in the recipe that will be run at test time.

  # requires:
    # Put any additional test requirements here.

about:
  #home:
  license: GPL
  summary: A fast and memory-efficient method for computing a few approximate singular values
    and singular vectors of large matrices.

# The original CRAN metadata for this package was:

# Package: irlba
# Type: Package
# Title: Fast partial SVD by implicitly-restarted Lanczos bidiagonalization
# Version: 1.0.3
# Date: 2013-10-31
# Author: Jim Baglama and Lothar Reichel
# Maintainer: Bryan W. Lewis <blewis@illposed.net>
# Description: A fast and memory-efficient method for computing a few approximate singular values and singular vectors of large matrices.
# Depends: R (>= 2.15.0)
# Imports: Matrix
# License: GPL
# Packaged: 2014-01-25 16:34:46 UTC; blewis
# NeedsCompilation: no
# Repository: CRAN
# Date/Publication: 2014-01-25 18:42:20

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
