package:
  name: m2-liblzma
  version: 5.4.4.1
source:
  - url: {{ msys2_pkg_url }}/liblzma-5.4.4-1-x86_64.pkg.tar.zst
    sha256: be9e236a9c1ab9a1e2e611d3f44a2b7338a62cc8c15fab0d75221db877fbfb16
    folder: binary

build:
  number: 0
  noarch: generic

requirements:
  host:
    - m2-conda-epoch
  run:
    - m2-sh
    - m2-libiconv
    - m2-gettext

about:
  home: https://tukaani.org/xz/
  license: GPL
  summary: Library for XZ and LZMA compressed files
