package:
  name: m2-libcbor
  version: 0.9.0.1
source:
  - url: {{ msys2_pkg_url }}/libcbor-0.9.0-1-x86_64.pkg.tar.zst
    sha256: 07cdebc6dba0aec6761f2a81d79254ecb19c6d1520336e28bc81fa1170bb60e1
    folder: binary

build:
  number: 0
  noarch: generic

requirements:
  host:
    - m2-conda-epoch
  run:


about:
  home: https://github.com/PJK/libcbor
  license: MIT
  summary: |
    A C library for parsing and generating CBOR, a general-purpose schema-less binary data format

extra:
  recipe-maintainers:
    - isuruf
