package:
  name: m2-libopenssl
  version: 3.1.2.1
source:
  - url: {{ msys2_pkg_url }}/libopenssl-3.1.2-1-x86_64.pkg.tar.zst
    sha256: 86d2b6012262a7ad71547f771794a35323fc49da0f9717093b3b9dc8d7284e35
    folder: binary

build:
  number: 0
  noarch: generic

requirements:
  host:
    - m2-conda-epoch
  run:


about:
  home: https://www.openssl.org
  license: Apache-2.0
  summary: |
    The Open Source toolkit for Secure Sockets Layer and Transport Layer Security

extra:
  recipe-maintainers:
    - isuruf
