package:
  name: m2-conda-epoch
  version: '20230914'
build:
  number: 0
  string: 0_x86_64  # [win and (arm64 or x86_64)]
  skip: True        # [not win]
  run_exports:
    - m2-conda-epoch {{ PKG_VERSION }} *_x86_64
requirements:
  run: []
  run_constrained:
    - msys2-conda-epoch <0.0a0
about:
  summary: epoch for m2 (not m2w64) packages
  description: |
    m2 packages are used as build tools for building packages
    on windows systems. These packages use the Cygwin runtime
    and therefore downstream conda packages should not link
    to these packages.

    Downstream packages should link to the m2w64 packages
    which used msvcrt runtime and now use ucrt runtime.

    We package m2 x86_64 packages for both win-64 and win-arm64
    platforms as win-arm64 can run x86_64 binaries and since
    there are no arm64 msys2 packages.
