package:
  name: m2-msys2-runtime
  version: 3.4.9.1
source:
  - url: {{ msys2_pkg_url }}/msys2-runtime-3.4.9-1-x86_64.pkg.tar.zst
    sha256: 6f720ee5cbdb3b862d5a4db100bcaa6faa4c10abb0572c4eecf22513d0ffb430
    folder: binary

build:
  number: 0
  noarch: generic

requirements:
  host:
    - m2-conda-epoch
  run:


about:
  home: https://www.cygwin.com/
  license: GPL
  summary: |
    Posix emulation engine for Windows

extra:
  recipe-maintainers:
    - isuruf
