package:
  name: m2-libgpg-error
  version: 1.47.1
source:
  - url: {{ msys2_pkg_url }}/libgpg-error-1.47-1-x86_64.pkg.tar.zst
    sha256: 9bb10e01b2ca163385290b1ce301e8e76d2fffb4ba4ee5d3ab4cb27c5ce5a4ee
    folder: binary

build:
  number: 0
  noarch: generic

requirements:
  host:
    - m2-conda-epoch
  run:
    - m2-bash
    - m2-libiconv
    - m2-libintl

about:
  home: https://gnupg.org
  license: LGPL-2.1-or-later
  summary: Support library for libgcrypt

extra:
  recipe-maintainers:
    - isuruf
