package:
  name: m2-perl-libwww
  version: 6.67.1
source:
  - url: {{ msys2_pkg_url }}/perl-libwww-6.67-1-any.pkg.tar.zst
    sha256: b5e32f6bc69efc6b3796168fae9079223980910e7e672de2b3bab98e1b25e96f
    folder: binary

build:
  number: 0
  noarch: generic

requirements:
  host:
    - m2-conda-epoch
  run:
    - m2-perl
    - m2-perl-Encode-Locale
    - m2-perl-File-Listing
    - m2-perl-HTML-Parser
    - m2-perl-HTTP-Cookies
    - m2-perl-HTTP-Daemon
    - m2-perl-HTTP-Date
    - m2-perl-HTTP-Negotiate
    - m2-perl-LWP-MediaTypes
    - m2-perl-Net-HTTP
    - m2-perl-URI
    - m2-perl-WWW-RobotRules
    - m2-perl-HTTP-Message
    - m2-perl-Try-Tiny

about:
  home: https://metacpan.org/dist/libwww-perl
  license: Artistic-1.0-Perl
  summary: The World-Wide Web library for Perl

extra:
  recipe-maintainers:
    - isuruf
