package:
  name: symengine
  version: 0.1

source:
  git_url: https://github.com/sympy/symengine
  git_tag: v0.1.0

requirements:
  build:
    - python
    - cython
    - numpy
    - gmp [unix]
    - mpir [win]
    - cmake
  run:
    - python
    - numpy
    - gmp [unix]
    - mpir [win]

test:
  imports:
    - symengine
  requires:
    - python
    - pytest
    - sympy

about:
    home: https://github.com/sympy/symengine
    license: BSD
