package:
  name: m2-libunistring
  version: 1.1.2
source:
  - url: {{ msys2_pkg_url }}/libunistring-1.1-2-x86_64.pkg.tar.zst
    sha256: e15b3b1f4a618e2212febc21e247a9a0ae1deb0bd57cc10fbb3ac9289c799136
    folder: binary

build:
  number: 0
  noarch: generic

requirements:
  host:
    - m2-conda-epoch
  run:
    - m2-libiconv

about:
  home: https://www.gnu.org/software/libunistring/
  license: LGPL-3.0-or-later OR GPL-2.0-or-later
  summary: |
    Library for manipulating Unicode strings and C strings.

extra:
  recipe-maintainers:
    - isuruf
