package:
  name: m2-gzip
  version: 1.13.1
source:
  - url: {{ msys2_pkg_url }}/gzip-1.13-1-x86_64.pkg.tar.zst
    sha256: 5f2fced435165f16a65ae82c6877a57d693f69e48916b842f6a4ef51c3e3f4a2
    folder: binary

build:
  number: 0
  noarch: generic

requirements:
  host:
    - m2-conda-epoch
  run:
    - m2-bash
    - m2-less

about:
  home: https://www.gnu.org/software/gzip/
  license: GPL3
  summary: |
    GNU compression utility

extra:
  recipe-maintainers:
    - isuruf
