package:
  name: m2-pcre2
  version: 10.42.1
source:
  - url: {{ msys2_pkg_url }}/pcre2-10.42-1-x86_64.pkg.tar.zst
    sha256: 25053c36e5de2171ab237628539c5b6dd29a1404b4fca1d4c1f196cc5d313c1a
    folder: binary

build:
  number: 0
  noarch: generic

requirements:
  host:
    - m2-conda-epoch
  run:
    - m2-libreadline
    - m2-libbz2
    - m2-zlib
    - m2-libpcre2_8 =10.42
    - m2-libpcre2_16 =10.42
    - m2-libpcre2_32 =10.42
    - m2-libpcre2posix =10.42

about:
  home: https://www.pcre.org/
  license: BSD
  summary: |
    A library that implements Perl 5-style regular expressions

extra:
  recipe-maintainers:
    - isuruf
