package:
  name: mingw-w64-ucrt-x86_64-gmp
  version: 6.3.0.1
source:
  - url: {{ m2w64_ucrt64_pkg_url }}/mingw-w64-ucrt-x86_64-gmp-6.3.0-1-any.pkg.tar.zst
    sha256: 64a728cb50165facf8105ef8f8f665f58ac5a3e8dfa96b7942a1862014283297
    folder: binary

build:
  number: 0

requirements:
  run:

  run_constrained:
    - msys2-conda-epoch <0.0a0

about:
  home: https://gmplib.org/
  license: LGPL3
  summary: |
    A free library for arbitrary precision arithmetic (mingw-w64)

extra:
  recipe-maintainers:
    - isuruf
