package:
  name: gmp
  version: 5.1.3

source:
  fn: gmp-5.1.3.tar.bz2
  url: ftp://ftp.gnu.org/gnu/gmp/gmp-5.1.3.tar.bz2

about:
  home: http://gmplib.org/
  license: LGPL 3 and GPL 2

test:
  files:
    - test.c
