package:
  name: m2-bsdtar
  version: 3.7.2.1
source:
  - url: {{ msys2_pkg_url }}/bsdtar-3.7.2-1-x86_64.pkg.tar.zst
    sha256: 193ce4a1c7bcf91f9086d85f13c5669f12bf58fe442da9053f09521911498eab
    folder: binary

build:
  number: 0
  noarch: generic

requirements:
  host:
    - m2-conda-epoch
  run:
    - m2-gcc-libs
    - m2-libbz2
    - m2-libiconv
    - m2-libexpat
    - m2-liblzma
    - m2-liblz4
    - m2-libopenssl
    - m2-libzstd
    - m2-zlib

about:
  home: https://libarchive.org/
  license: BSD
  summary: Multi-format archive and compression library
