package:
  name: keras
  version: 0.1.1

source:
  fn: Keras-0.1.1.tar.gz
  url: https://pypi.python.org/packages/source/K/Keras/Keras-0.1.1.tar.gz
  md5: fb1815ef1dc713d599e8a9a0948f0614

requirements:
  build:
    - python
    - setuptools
    - numpy
    - scipy
    - theano

  run:
    - python
    - numpy
    - scipy
    - theano
    - six

test:
  # Python imports
  imports:
    - keras.models
    - keras.layers.core
    - keras.optimizers

about:
  home: https://github.com/fchollet/keras/
  license: BSD License
