package:
  name: m2-libpcre2posix
  version: 10.42.1
source:
  - url: {{ msys2_pkg_url }}/libpcre2posix-10.42-1-x86_64.pkg.tar.zst
    sha256: 6a3195cac749789bda577dbf7be4f30086c0dcca6fbbfd09b1157d9212f7f96d
    folder: binary

build:
  number: 0
  noarch: generic

requirements:
  host:
    - m2-conda-epoch
  run:
    - m2-libpcre2_8=10.42

about:
  home: https://www.pcre.org/
  license: BSD
  summary: A library that implements Perl 5-style regular expressions

extra:
  recipe-maintainers:
    - isuruf
