package:
  name: m2-libhogweed
  version: 3.9.1.1
source:
  - url: {{ msys2_pkg_url }}/libhogweed-3.9.1-1-x86_64.pkg.tar.zst
    sha256: 3f5fc78a3bd917955dd8601849c75b1a48e69a8fff787330408c0992318c22ae
    folder: binary

build:
  number: 0
  noarch: generic

requirements:
  host:
    - m2-conda-epoch
  run:
    - m2-gmp

about:
  home: https://www.lysator.liu.se/~nisse/nettle/
  license: GPL-2.0-or-later OR LGPL-3.0-or-later
  summary: |
    A low-level cryptographic library

extra:
  recipe-maintainers:
    - isuruf
